### PR TITLE
System Update

### PR DESCRIPTION
**Pull request by Omnija**
Neogeo Pocket Color
Wonderswan Color

### CODE REVIEW

**Comment by HerbFargus** [comment]
It's unlikely these will be split in the retropie code (same reason why megadrive and genesis were never split) but I'll add them into the theme as it does no harm. Thanks.

**Comment by Omnija** [comment]
Thought megadrive and genesis were the same thing? But i figured it would be good to split them for the same reason gbc and gb are separated to either have the options of choosing colour or non colour; While having the folder to correspond to that selection.
An idea would be to leave the original code but add the second line in, incase other users do the same as i do?

**Comment by DrMaxwell** [comment]
megadrive and genesis are different region based systems

**Comment by HerbFargus** [comment]
True but basically the exact same hardware, whereas gameboy and gameboy colour are separate pieces of hardware. The themes are both there but in the code Jools didn't care to differentiate them. Thegamesdb also merged them as one platform (the scraper api retropie uses)

**Comment by DrMaxwell** [comment]
Gameboy and Gamboy Color are different machines altogether with different
capabilities and peripheral devices; whereas, the Sega Genesis (USA), Sega
Megadrive (Europe/Japan/South America/Hong Kong) are simply regionally
different in terms of their software releases.

**Pull request merged**
