### PR TITLE
Add steam for limelight/moonlight

### PR DESCRIPTION
**Pull request by sirskunkalot**
I resembled a fitting logo and vectorized a steampad. Seems nobody has done this for carbon or at least shared it. I am fairly new to svg (and git - first commit, yay :)), but I think it fits nicely.

### CODE REVIEW

**Comment by HerbFargus** [comment]
Have you tested it within emulationstation?

**Comment by sirskunkalot** [comment]
Yeah, sure. I made it for my own installation (new RetroPie 3.5 image).

**Comment by HerbFargus** [comment]
I ask just cause sometimes emulationstation doesn't render svgs that look fine when drawn on a pc. Thanks, looks great.

**Comment by sirskunkalot** [comment]
Thanks. Had that very problem myself, as I first just had a path with colored edges, Seems like ES just likes "double-paths" with a colored "body" (sorry, don't know the right terminology). Same with the text: Had to render it to a path first, otherwise it did not show up.

**Comment by HerbFargus** [comment]
Yeah it wants the strokes as paths and the fills as paths. Simple enough to do, but super annoying when it's forgotten, also makes the svg a lot larger than in needs to be. Likelihood is emulationstation is just using an old library for svgs.

**Comment by DrMaxwell** [comment]
Just open the svg, trace object, save as SVG with attributes correctly selected.

**Pull request merged**
