### PR TITLE
add video support

### PR DESCRIPTION
**Pull request by jrassa**

### CODE REVIEW

**Comment by robertybob** [comment]
Wow is it really this simple to add support for videos? May actually attempt this for my theme..one day lol

**Comment by HerbFargus** [comment]
This needs to be tested thoroughly before committing. just to make sure it doesnt break the non video version of ES as this is the default theme for every retropie image. so interested in some feedback on this before merging

**Comment by jrassa** [comment]
I updated this to use maxSize for videos to preserve aspect ratio (https://github.com/RetroPie/EmulationStation/pull/102) and to use the feature element (https://github.com/RetroPie/EmulationStation/pull/96) to maintain backward compatibility with non video version of ES.

**Comment by HerbFargus** [comment]
Thanks for the fixes. I'll see if I can get some time to test it after work as I'd like the default theme to have video support sooner than later

**Comment by HerbFargus** [comment]
@jrassa 

Where do marquees fit into all of this? or are they something that would have to be coded into the theme design and we just assume people don't use them for the default carbon theme?

**Comment by HerbFargus** [comment]
Actually ignore the above, this is how the current theme looks (i had forgotten to make some last updates):

updates

its looking pretty good to me

**Comment by HerbFargus** [comment]
Well I tested on the new and old version of ES and it seems to be functioning without breaking so I'm going to merge this.

thanks!

**Pull request merged**
